### PR TITLE
Make the package play nicely with Webpack

### PR DESCRIPTION
**Pull request by jcfrancisco**
Webpack's bundler does not like dynamic requires.

### CODE REVIEW

**Comment by atheken** [comment]
@jcfrancisco I'm a little bit confused about this, mostly because I don't have a lot of familiarity with webpack, but my understanding was that it was for minifying/bundling code for the browser. 

Postmark's API does not support CORS (and probably won't for awhile, as this would expose Server/Account tokens in the browser), so including the package in the client side is a bit unorthodox, and probably won't yield the expected results.. am I missing something?

**Comment by jcfrancisco** [comment]
@atheken Webpack has some support for rolling up a bundle you can run on the server-side through Node as well. We use it for a few of our apps!

**Comment by alexeybondarenko** [comment]
+1. I also use webpack for server side code. I roll up a bundle of server code for decreasing size of application, what I pack inside Docker container. In result, my react js + node js app with alpine linux has around 50 mb (17-20 mb compressed). I've also created PR for this #10.

**Comment by atheken** [comment]
Thanks. 1.4.0 has this fix in place!

**Comment by jcfrancisco** [comment]
@atheken TYVM! I'm deprecating a temporary fork I made on NPM and will note to use 1.4.0 or above. As a side note, I think you can even revert this PR; since you made the same change in a previous commit we're now requiring `http` and `https` twice. :)

**Comment by atheken** [comment]
Yep. I see that. Published 1.4.1 with the tweak. And, you're very welcome, thanks for the PR!

**Pull request merged**
